# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLoginwithnopassword():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_loginwithnopassword(self):
    # Test name: login_with_no_password
    # Step # | name | target | value
    # 1 | open | /LoginV4/login.xhtml | 
    self.driver.get("https://my.ny.gov/LoginV4/login.xhtml")
    # 2 | setWindowSize | 1010x912 | 
    self.driver.set_window_size(1010, 912)
    # 3 | type | id=loginform:username | dvir.aharoni
    self.driver.find_element(By.ID, "loginform:username").send_keys("dvir.aharoni")
    # 4 | type | id=loginform:password | Dv1raharoni1605
    self.driver.find_element(By.ID, "loginform:password").send_keys("Dv1raharoni1605")
    # 5 | click | id=loginform:password | 
    self.driver.find_element(By.ID, "loginform:password").click()
    # 6 | type | id=loginform:password | kuku
    self.driver.find_element(By.ID, "loginform:password").send_keys("kuku")
    # 7 | click | id=loginform | 
    self.driver.find_element(By.ID, "loginform").click()
    # 8 | click | css=#loginform\3AsigninButton > .ui-button-text | 
    self.driver.find_element(By.CSS_SELECTOR, "#loginform\\3AsigninButton > .ui-button-text").click()
  
